# -*- coding: utf-8 -*-
"""CodeInference3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IM8jNCXKuiRRvmBNGSoJyahGQ5PFnxJN

###**UTS MODEL DEPLOYMENT**
#####Putri Maysa Adira
#####2702372826
#####LB09
#####No 3 (Dataset B)
"""

import streamlit as st
import pandas as pd
import joblib

st.title("🧠 Hotel Booking Cancellation Prediction")

# Load model dan encoder
best_model = joblib.load('best_model.pkl')
booking_status_encode = joblib.load('booking_status_encode.pkl')
label_encoder = joblib.load('label_encoder.pkl')

if best_model and booking_status_encode:
    st.success("✅ Model dan encoder berhasil dimuat!")

    # Test cases
    testcases = {
        "Default Input": {
            'no_of_adults': [2],
            'no_of_children': [1],
            'no_of_weekend_nights': [2],
            'no_of_week_nights': [3],
            'type_of_meal_plan_Meal Plan 2': 1,
            'type_of_meal_plan_Meal Plan 3': 0,
            'type_of_meal_plan_Not Selected': 0,
            'room_type_reserved_Room_Type 2': 0,
            'room_type_reserved_Room_Type 3': 0,
            'room_type_reserved_Room_Type 4': 1,
            'room_type_reserved_Room_Type 5': 0,
            'room_type_reserved_Room_Type 6': 0,
            'room_type_reserved_Room_Type 7': 0,
            'lead_time': 35,
            'arrival_year': 2018,
            'arrival_month': 5,
            'arrival_date': 12,
            'market_segment_type_Corporate': 0,
            'market_segment_type_Offline': 0,
            'market_segment_type_Online': 1,
            'market_segment_type_Complementary': 0,
            'repeated_guest': 0,
            'no_of_previous_cancellations': 0,
            'no_of_previous_bookings_not_canceled': 0,
            'avg_price_per_room': 105.5,
            'no_of_special_requests': 1,
            'room_type_reserved_Room_Type 1': 0,
            'type_of_meal_plan_Meal Plan 1': 0,
            'market_segment_type_Aviation': 0
        },
        "Test Case 1": {
            'no_of_adults': [1],
            'no_of_children': [0],
            'no_of_weekend_nights': [0],
            'no_of_week_nights': [1],
            'type_of_meal_plan_Meal Plan 2': 0,
            'type_of_meal_plan_Meal Plan 3': 0,
            'type_of_meal_plan_Not Selected': 1,
            'room_type_reserved_Room_Type 2': 1,
            'room_type_reserved_Room_Type 3': 0,
            'room_type_reserved_Room_Type 4': 0,
            'room_type_reserved_Room_Type 5': 0,
            'room_type_reserved_Room_Type 6': 0,
            'room_type_reserved_Room_Type 7': 0,
            'lead_time': 300,
            'arrival_year': 2018,
            'arrival_month': 8,
            'arrival_date': 25,
            'market_segment_type_Corporate': 1,
            'market_segment_type_Offline': 0,
            'market_segment_type_Online': 0,
            'market_segment_type_Complementary': 0,
            'repeated_guest': 0,
            'no_of_previous_cancellations': 1,
            'no_of_previous_bookings_not_canceled': 0,
            'avg_price_per_room': 300.0,
            'no_of_special_requests': 0,
            'room_type_reserved_Room_Type 1': 0,
            'type_of_meal_plan_Meal Plan 1': 0,
            'market_segment_type_Aviation': 0
        },
        "Test Case 2": {
            'no_of_adults': [2],
            'no_of_children': [2],
            'no_of_weekend_nights': [2],
            'no_of_week_nights': [5],
            'type_of_meal_plan_Meal Plan 2': 0,
            'type_of_meal_plan_Meal Plan 3': 1,
            'type_of_meal_plan_Not Selected': 0,
            'room_type_reserved_Room_Type 2': 0,
            'room_type_reserved_Room_Type 3': 1,
            'room_type_reserved_Room_Type 4': 0,
            'room_type_reserved_Room_Type 5': 0,
            'room_type_reserved_Room_Type 6': 0,
            'room_type_reserved_Room_Type 7': 0,
            'lead_time': 20,
            'arrival_year': 2018,
            'arrival_month': 11,
            'arrival_date': 9,
            'market_segment_type_Corporate': 0,
            'market_segment_type_Offline': 0,
            'market_segment_type_Online': 1,
            'market_segment_type_Complementary': 0,
            'repeated_guest': 1,
            'no_of_previous_cancellations': 0,
            'no_of_previous_bookings_not_canceled': 5,
            'avg_price_per_room': 85.0,
            'no_of_special_requests': 2,
            'room_type_reserved_Room_Type 1': 0,
            'type_of_meal_plan_Meal Plan 1': 0,
            'market_segment_type_Aviation': 0
        }
    }

    # Pilihan test case
    selected_case = st.selectbox("📂 Pilih Test Case", list(testcases.keys()))
    df_input = pd.DataFrame(testcases[selected_case])

    # Urutan fitur sesuai model
    feature_order = [
        'no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights', 'lead_time',
        'arrival_year', 'arrival_month', 'arrival_date', 'repeated_guest', 'no_of_previous_cancellations',
        'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests',
        'type_of_meal_plan_Meal Plan 1', 'type_of_meal_plan_Meal Plan 2', 'type_of_meal_plan_Meal Plan 3',
        'type_of_meal_plan_Not Selected',
        'room_type_reserved_Room_Type 1', 'room_type_reserved_Room_Type 2', 'room_type_reserved_Room_Type 3',
        'room_type_reserved_Room_Type 4', 'room_type_reserved_Room_Type 5', 'room_type_reserved_Room_Type 6',
        'room_type_reserved_Room_Type 7',
        'market_segment_type_Aviation', 'market_segment_type_Complementary', 'market_segment_type_Corporate',
        'market_segment_type_Offline', 'market_segment_type_Online'
    ]
    df_input = df_input[feature_order]

    st.subheader("📋 Data yang Digunakan:")
    st.dataframe(df_input)

    # Prediksi
    prediction = best_model.predict(df_input)[0]
    probability = best_model.predict_proba(df_input)[:, 1][0]

    # Tampilkan hasil prediksi
    status = booking_status_encode.get(prediction, "Unknown")
    st.subheader("🎯 Hasil Prediksi:")
    st.success(f"Status Booking: {status}")
    st.info(f"🔢 Probabilitas Pembatalan: {probability:.2%}")

else:
    st.warning("❗ Gagal memuat model atau encoder.")